language: java
sudo: false # faster builds
jdk:
 - oraclejdk8
test:
 post:
  - if [ -e ./gradlew ]; then ./gradlew codeCoverageReport;else gradle codeCoverageReport;fi
  - bash <(curl -s https://codecov.io/bash)