language: java
sudo: false # faster builds
jdk:
 - openjdk8
before_script:
 - chmod +x gradlew
script:
 - ./gradlew --refresh-dependencies check
 - ./gradlew codeCoverageReport
after_success:
 - bash <(curl -s https://codecov.io/bash)
